#!/bin/bash


TARGET_DIR="./bin"
TEMPLATE_DIR="./archive/template"


DIR_NAME=$(basename "$(pwd)")
if [ "$DIR_NAME" != "commands" ]; then
  echo "commandsディレクトリで実行してください"
  exit 1
fi

if [ -d "$TARGET_DIR" ]; then
  echo "TARGET_DIRを削除しています: $TARGET_DIR"
  rm -rf "${TARGET_DIR:?}"/*
else
  echo "ディレクトリが存在しません: $TARGET_DIR"
fi

# TEMPLATE_DIRの中身をTAEGET_DIRにコピー
if [ -d "$TEMPLATE_DIR" ]; then
  echo "TEMPLATE_DIRをコピーしています: $TEMPLATE_DIR"
  cp -r "$TEMPLATE_DIR"/* "$TARGET_DIR"
else
  echo "ディレクトリが存在しません: $TEMPLATE_DIR"
fi

echo "削除が正常に完了しました"
